### ISSUE TITLE
Goal achieved? 

### ISSUE THREAD

**Issue by nohwnd** [fflaten/fflaten#1]
I see one of your goals is: "Contribute more to open source", I think with all the great contributions to Pester you've done lately, you can consider that goal done. 👏👏👏

Do you have more online presence than just github and stackoverflow? I'd love to mention you and link back to you in release notes and on twitter.

**Comment by fflaten** [comment]
Thanks! Not sure if the goal can ever be done. 😅 This is only the start I hope, though I've had a bit extra time lately to kick-start it. I learn by doing, so being able to contribute to projects that many, including me, depend on is perfect.

Not active on twitter yet, so github/SO and linkedin (CV) is mostly it atm.

**Comment by nohwnd** [comment]
I don't see your linked in anywhere. Could you link me to it please? 😕

**Comment by fflaten** [comment]
www.linkedin.com/in/frodeflaten

**Comment by fflaten** [comment]
Updated profile with linkedin and twitter even though they're both very inactive 👍
